// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aradork.Models;

#nullable disable

namespace aradork.Migrations
{
    [DbContext(typeof(aradorkDBContext))]
    [Migration("20250202200225_FixPrimaryKeyGeneration")]
    partial class FixPrimaryKeyGeneration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("aradork.Models.Agendum", b =>
                {
                    b.Property<string>("Firstname")
                        .HasMaxLength(364)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .HasMaxLength(68)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastConnection")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .HasMaxLength(48)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mail")
                        .HasMaxLength(39)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Postion")
                        .HasMaxLength(90)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(74)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("URL");

                    b.HasKey("Firstname")
                        .HasName("PK_Agenda_Firstname");

                    b.ToTable("agenda", (string)null);
                });

            modelBuilder.Entity("aradork.Models.AragonDorks", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("DorkValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AragonDorks", (string)null);
                });

            modelBuilder.Entity("aradork.Models.Secrets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Secrets");
                });
#pragma warning restore 612, 618
        }
    }
}
